### PR TITLE
Condensed and updated PyNN script

### PR DESCRIPTION
**Pull request by apdavison**
I have condensed the PyNN script from ~1600 lines to ~400, and updated the units of the injected currents (from pA to nA) to work with the latest development version of PyNN (https://github.com/NeuralEnsemble/PyNN/commit/edade7).

### CODE REVIEW

**Comment by apdavison** [comment]
@pgleeson ok to merge this? The code is much improved, and only panels L and R are now qualitatively different to the published results. I'll update the wiki once it's merged.

izhikevich2004_nest_20150903-124829

**Comment by pgleeson** [comment]
Excellent! Glad you saw the changes I had made this morning.

Have also just added the NEURON & MATLAB versions Bill Lytton & Salvador Dura-Bernal have recently updated on ModelDB. Will try to get OMV tests in place across all versions...

**Comment by apdavison** [comment]
When I try to upload a new figure to the wiki, I get “Internal Server Error”. Any ideas?

**Comment by pgleeson** [comment]
Existing issue for this here: https://github.com/OpenSourceBrain/redmine/issues/197.

Thinking about moving most of the OSB wikis to markdown in the GH repos. It's easy to link to them and have the same displayed on http://www.opensourcebrain.org [using entries like github:README.md](http://www.opensourcebrain.org/docs#Creating_Your_Own_Project). Easier for people to find the docs then if they're just browsing the GH project & for others to do pull requests on them...

**Comment by apdavison** [comment]
:+1: for moving the wikis

**Comment by adrianq** [comment]
@apdavison @pgleeson You can now upload images to the wiki however I would recommend to go for the markdown approach. It is good to have both repo and osb wiki synchronised and markdown is quite powerful

**Pull request merged**
