### PR TITLE
fast python numba JIT model that reproduces 2007.m

### PR DESCRIPTION
**Pull request by russelljjarvis**
Hi there people at OSB.

I created an Izhikevich simulation that uses the tool numba JIT, and yields very fast simulation times inside a basic python environment.  Also the model has the advantage that it uses the standard formats: python-quantities, and neo. I think the general approach is useful, and I have also done the same for the Adaptive Exponential model.

[Here](https://github.com/russelljjarvis/IzhikevichModel/blob/master/numba/faster_izhikevich_model.ipynb
) is a notebook demonstrating the models speed and its ability to reproduce 2007.m.

### CODE REVIEW

**Comment by rgerkin** [comment]
This can be thought of as another set of reference implementations for some of these models, but with the benefit of being open source, fast, and readable.  We use some of these internally for optimization or just to do some quick tests, before choosing parameters for corresponding NeuroML versions.

**Review by russelljjarvis — COMMENTED** [review]
I can see now that neatly/properly integrating numba model simulations I would need to create files in the OSB-model validation framework. 

I have started doing that here:
https://github.com/russelljjarvis/osb-model-validation/blob/master/omv/engines/numba_izhi.py
https://github.com/russelljjarvis/osb-model-validation/blob/master/omv/engines/getnumba.py

I can also add an [Adaptive Exponential](https://github.com/russelljjarvis/jit_hub/blob/main/numba_adexp.py
) model to the numba engine.
But I may need advice about how to apply the numba engine to make it eligible for model testing.

**Comment by pgleeson** [comment]
Thanks for this @russelljjarvis @rgerkin. Great to have another reference implementation.

For integrating/testing with omv, one simpler option is just to run the appropriate python script in the engine Brian2, as here: https://github.com/OpenSourceBrain/WilsonCowan/blob/master/Python/.test.slow.omt, as this will provide a python environment (the fact that Brian2 is there doesn't matter), and you just have to make sure the appropriate python packages are installed in the travis file.

**Comment by russelljjarvis** [comment]
Hi @pgleeson, awesome, thanks.

Yes, I will check out this option for using brian2 omv.

**Pull request merged**
